### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by saberzaid** [penetrarnya-tm/WeaponizeKali.sh#5]
hello 
so i run the updated tool and this errors shown : 

[+] Downloaded release: adcspwn.exe
[+] Downloaded raw file: adrecon.ps1
[+] Downloaded raw file: asreproast.ps1
[+] Downloaded raw file: accesschk-accepteula.zip
[+] Downloaded raw file: accesschk.zip
[+] Downloaded raw file: discover-psmsexchangeservers.ps1
[+] Downloaded raw file: discover-psmssqlservers.ps1
[+] Downloaded raw file: domainpasswordspray.ps1
[+] Downloaded release: hivenightmare.exe
[+] Downloaded raw file: hive.exe
[+] Cloned repository: ShadowSteal
main: line 1099: nimble: command not found
nim c --d:mingw --d:release --cpu=amd64 --app=console --deadCodeElim:on --opt:size --stackTrace:off --lineTrace:off --app=console --cpu=amd64 --out=bin/ShadowSteal.exe src/ShadowSteal.nim
make: nim: No such file or directory
make: *** [Makefile:20: ShadowSteal.exe] Error 127
mv: cannot stat 'bin/ShadowSteal.exe': No such file or directory
chmod: cannot access '../shadowsteal.exe': No such file or directory

**Comment by snovvcrash** [comment]
Hey. It's seems like you do not have `nimble` installed. It's being installed in [this](https://github.com/penetrarnya-tm/WeaponizeKali.sh/blob/05b6392d77e76b13604093fe2ba41f090fc63080/WeaponizeKali.sh#L358-L364) part of the script.
Try to `sudo apt install nim -y` manually.
